# Generated by Django 4.0.4 on 2022-05-15 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('trans_date', models.DateTimeField(verbose_name='Date')),
                ('trans_status', models.CharField(choices=[('closed', 'CLOSED'), ('reserved', 'RESERVED'), ('pending', 'PENDING')], default='pending', max_length=20, verbose_name='Status Transaction')),
                ('aprobation', models.BooleanField(default=False, verbose_name='Status Approved')),
                ('final_charge', models.BooleanField(default=False, verbose_name='Final Charge')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.company', verbose_name='Company ID')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
